### ISSUE TITLE
The install command for Debian doesn't work

### ISSUE THREAD

**Issue by ruanjiaxing** [Codeon-GmbH/mulle-clang#37]
I'm using Debian Bullseye (Sparky Linux) and the command using curl to download the deb package doesn't work. I notice even if I manually replace the result of lsb_release with the value for Buster or Stretch it still doesn't work. My computer doesn't have enough RAM so I can't build clang from source. Please check this document section about installing on Debian. If you didn't support Bullseye please consider to support it or let me know if I could install using the package for Debian Stable. Thanks.

**Comment by codeon-nat** [comment]
Yes, the distribution is currently a bit too ubuntu centric :)

Looking at this table which maps ubuntu to debian code names, if you take focal you should be OK for bullseye. I agree that the shell script piece is not working.

```
20.04  focal      bullseye/ sid   - 11
19.10  eoan       buster  / sid   - 10
19.04  disco      buster  / sid
18.10  cosmic     buster  / sid
18.04  bionic     buster  / sid
17.10  artful     stretch / sid   - 9
17.04  zesty      stretch / sid
16.10  yakkety    stretch / sid
16.04  xenial     stretch / sid
15.10  wily       jessie  / sid   - 8
15.04  vivid      jessie  / sid
14.10  utopic     jessie  / sid
14.04  trusty     jessie  / sid
13.10  saucy      wheezy  / sid   - 7
13.04  raring     wheezy  / sid
12.10  quantal    wheezy  / sid
12.04  precise    wheezy  / sid
11.10  oneiric    wheezy  / sid
11.04  natty      squeeze / sid   - 6
10.10  maverick   squeeze / sid
10.04  lucid      squeeze / sid
```
So:

```
curl -O -L http://download.codeon.de/dists/focal/main/binary-amd64/mulle-clang-10.0.0.2-focal-amd64.deb && \
sudo dpkg --install mulle-clang-10.0.0.2-focal-amd64.deb
```
should do the trick. If it doesn't please let me know and I will try it with a proper debian VM or docker.

P.S. Updated and fixed the install instructions for debian

**Comment by ruanjiaxing** [comment]
Yes, the updated install instructions worked. I will close the issue.
