### ISSUE TITLE
Debian buster install download is missing

### ISSUE THREAD

**Issue by darkoverlordofdata** [Codeon-GmbH/mulle-clang#38]
I'm following the instructions at [https://github.com/Codeon-GmbH/mulle-clang](https://github.com/Codeon-GmbH/mulle-clang) , where the link for debian buster links to [http://download.codeon.de/dists/eoan/main/binary-amd64/mulle-clang-10.0.0.2-bionic-amd64.deb](http://download.codeon.de/dists/eoan/main/binary-amd64/mulle-clang-10.0.0.2-bionic-amd64.deb).

The package is missing. I get:
```
Not Found
The requested URL was not found on this server.

```

**Comment by codeon-nat** [comment]
Thanks. I fixed the link.

**Comment by darkoverlordofdata** [comment]
This was also resolved by https://github.com/MulleFoundation/foundation-developer/issues/3    

Thanks for your quick reply!
