### ISSUE TITLE
Optimizer falsely reuses parameter block

### ISSUE THREAD

**Issue by mulle-nat** [Codeon-GmbH/mulle-clang#9]
I am pretty sure the compiler does the wrong thing (not using a new parameter block) when tail call optimizing this:

```
- (void) foo:(id) a :(id) b
{
   [self bar:&a :&b];
}
```

Workaround: Compile with -O0 for now.
Todo: introduce compiler flag to turn off this optimization 
Fix it, by checking call arguments for taints.

**Comment by codeon-nat** [comment]
This appears to be fixed now.
